name: Deploy
on:
  push:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: linting
        shell: bash
        run: "echo linting"

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: check dir
        shell: bash
        run: "$(pwd) && ls -al "
      - name: test
        shell: bash
        run: "echo linting"

  build:
    name: build
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: echo branch name
        shell: bash
        run: "echo ${{ steps.extract_branch.outputs.branch }}"
      - name: build
        shell: bash
        run: "echo linting"

  delivery:
    name: delivery
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: echo branch name
        shell: bash
        run: "echo ${{ build.steps.extract_branch.outputs.branch }}"
      - name: echo branch name
        shell: bash
        run: "echo ${{ jobs.build.steps.extract_branch.outputs.branch }}"
      - name: delivery
        shell: bash
        run: "echo linting"

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs:
      - delivery

    steps:
      - name: deploy
        shell: bash
        run: "echo linting"

  source-branch:
    name: kich when merged
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: echo source branch
        shell: bash
        run: "merged"
