name: Deploy
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: linting
        shell: bash
        run: "echo linting"

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: current dir
        shell: bash
        run: "pwd"
      - name: check dir
        shell: bash
        run: "ls -al"
      - name: test
        shell: bash
        run: "echo linting"
      - run: env
      - run: echo ${GITHUB_BASE_REF}
      - run: echo ${{ github }}

  build:
    name: build
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: echo branch name
        shell: bash
        run: "echo ${{ steps.extract_branch.outputs.branch }}"
      - name: build
        shell: bash
        run: "echo linting"

  sharing-variables-among-jobs:
    name: sharing variables between jobs
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: math-homework.txt
  using-variables-among-jobs:
    name: Multiply by 9
    needs: sharing-variables-among-jobs
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: homework
      - shell: bash
        run: |
          value=`cat homework/math-homework.txt`
          expr $value \* 9 > homework/math-homework.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: homework/math-homework.txt

  display-variables-among-jobs:
    name: Display results
    needs: using-variables-among-jobs
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v1
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat homework/math-homework.txt`
          echo The result is $value

  delivery:
    name: delivery
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: delivery
        shell: bash
        run: "echo linting"

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs:
      - delivery

    steps:
      - name: deploy
        shell: bash
        run: "echo linting"

  source-branch:
    name: kick when merged
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: echo source branch
        shell: bash
        run: "merged"
